services:

  oksydan.is_favoriteproducts.grid.data.factory.favorite_list_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@Oksydan\IsFavoriteProducts\Grid\Query\FavoriteListQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'is_favoriteproducts_list'

  oksydan.is_favoriteproducts.grid.favorite_list_grid_factory:
    public: true
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@Oksydan\IsFavoriteProducts\Grid\Definition\Factory\FavoriteListGridDefinitionFactory'
      - '@Oksydan\IsFavoriteProducts\Grid\Data\Factory\FavoriteListGridDataFactory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

