imports:
  - { resource: ../common.yml }
  - { resource: grid.yml }

services:
  _defaults:
    public: false
    autoconfigure: true
    autowire: true
    bind:
      $module: '@oksydan.is_favoriteproducts.module'
      $context: '@oksydan.is_favoriteproducts.context'
      $dbPrefix: '%database_prefix%'
      $cacheableHooksCollection: !tagged oksydan.is_favoriteproducts.cacheable_hook
      $formBuilderModifier: '@form.form_builder_modifier'
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()'
      $favoriteListDataFactory: '@oksydan.is_favoriteproducts.grid.data.factory.favorite_list_data_factory'
      $contextAdapter: '@prestashop.adapter.shop.context'

  _instanceof:
    Oksydan\IsFavoriteProducts\Hook\AbstractCacheableDisplayHook:
      tags: [ 'oksydan.is_favoriteproducts.cacheable_hook' ]

  Oksydan\IsFavoriteProducts\:
    resource: '../../src/*'
    exclude:
      - '../../src/{DTO,Entity,Controller}'
      - '../../src/index.php'
      - '../../src/*/index.php'

  Oksydan\IsFavoriteProducts\Hook\:
    public: true
    resource: '../../src/Hook/*'
    exclude:
      - '../../src/Hook/index.php'
