services:
  _defaults:
    public: false

  oksydan.is_favoriteproducts.module:
    class: Is_favoriteproducts
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'is_favoriteproducts'

  oksydan.is_favoriteproducts.context:
    class: Context
    factory: [ '\Context', getContext ]
